Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -1,7 +1,7 @@
 #
 # https://github.com/P3TERX/Actions-OpenWrt
 #
-# File: .github/workflows/openwrt-bulder.yml
+# File: .github/workflows/openwrt-builder.yml
 # Description: Build OpenWrt using GitHub Actions
 #
 # Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
@@ -113,7 +113,7 @@ jobs:
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    -- name: Compile the firmware
+    - name: Compile the firmware
       id: compile
       run: |
         set -e
@@ -121,11 +121,14 @@ jobs:
         echo -e "$(nproc) thread compile"
         echo "status=failed" >> $GITHUB_OUTPUT
         
-        # 先用多线程编译，如果失败自动降为单线程输出详细报错信息 (V=s)
-        make -j$(nproc) || make -j1 V=s || {
-          echo "❌ Make failed"
-          exit 1
-        }
+        # 多线程并行编译失败后降级为单线程 (V=s) 打印精准报错
+        if ! make -j$(nproc); then
+            echo "⚠️ 并行编译失败，正在切换单线程调试模式 (V=s) 捕获错误..."
+            if ! make -j1 V=s; then
+                echo "❌ Make failed"
+                exit 1
+            fi
+        fi
         
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
