Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -113,17 +113,20 @@ jobs:
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: Compile the firmware
+    -- name: Compile the firmware
       id: compile
       run: |
         set -e
         cd openwrt
         echo -e "$(nproc) thread compile"
         echo "status=failed" >> $GITHUB_OUTPUT
-        if ! ( make -j$(nproc) || make -j1 V=s ); then
-            echo "❌ Make failed"
-            exit 1
-        fi
+        
+        # 先用多线程编译，如果失败自动降为单线程输出详细报错信息 (V=s)
+        make -j$(nproc) || make -j1 V=s || {
+          echo "❌ Make failed"
+          exit 1
+        }
+        
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
